EduOpsSolutions/EduOps

- client/src/components/buttons/DownloadButton.js
- client/src/components/buttons/RequestButton.js
- client/src/components/buttons/SmallButton.js
- client/src/components/modals/DocumentRequestsModal.js
- client/src/components/modals/ForgetPasswordModal.js
- client/src/components/modals/RequestDocumentModal.js
- client/src/components/modals/RequestDocumentSentModal.js
- client/src/components/navbars/StudentNav.js
- client/src/components/textFields/LabelledInputField.js
- client/src/components/textFields/LargeInputField.js
- client/src/components/textFields/SelectField.js
- client/src/pages/public/SignUp.js
- client/src/pages/student/documents/Documents.js
- client/tailwind.config.js
- Added documents page
- Created components for download and request buttons
- Added Document Request Modal
- Added See Document Requests Modal
To Do:
- Implement backend logic for document page
- in the document request modal, add backend logic to display the document name for its title
- Implement backend logic to display document requests.
- Try to find a better icon in See requests button
- Some comments are already provided for guidance :)
> Added Documents Page for Students

- client/src/App.js
- client/src/components/modals/ForgetPasswordModal.js
- client/src/components/modals/GradeNotReadyModal.js
- client/src/components/navbars/StudentNav.js
- client/src/pages/public/SignUp.js
- client/src/pages/student/grades/Grades.js
- Created grades page for students
- Added a modal that displays if grades are not ready
- Added to do comments in file
Note: 
- Still need to add modal that displays the grades of students with an inbuild file previewer
- Change icons to what's desired
> Added Grades Page for Students

- client/src/App.js
- client/src/components/layout/AdminLayout.js
- client/src/components/layout/TeacherLayout.js
- client/src/components/modals/devLoginModal.js
- client/src/components/navbars/AdminNav.js
- client/src/components/navbars/StudentNav.js
- client/src/components/navbars/TeacherNav.js
- client/src/pages/admin/home/Home.js
- client/src/pages/public/Login.js
- client/src/pages/teacher/home/Home.js
- Added temporary login modal (will be removed once auth logic is implemented) to move between the user pages
- Added teacher and admin navbar
- Created admin and teacher layouts
> Added teacher and admin navbars and temporary login modal

- client/src/components/textFields/FileUploadButton.js
- client/src/pages/public/SignUp.js
- Added handleFileChange function
- Improved FileUploadButton ui
- Removed deceased checkbox
> E-4 - Enrollment Form

- client/src/App.js
- client/src/components/modals/common/TransactionHistoryModal.js
- client/src/components/navbars/StudentNav.js
- client/src/pages/student/Assessment.js
- Added Assessment screen for students
- Added the route path for student Assessment in App.js
- Added Transaction History modal
- Added navigation for the Assessment screen in student navbar using Payment link
- Added navigation to Ledger through the Ledger button
> P-1 Assessment Screen (Student)

- client/src/App.js
- client/src/components/navbars/AdminNav.js
- client/src/pages/admin/EnrollmentPeriod.js
- client/src/pages/admin/EnrollmentRequests.js
- client/src/utils/axios.js
Implemented initial design for enrollment periods
Updated App.js 
Added initial design for EnrollmentPeriod.js
> E-1 [FE] Manage Enrollment Periods

- client/src/App.js
- client/src/components/navbars/AdminNav.js
- client/src/pages/admin/EnrollmentRequests.js
Implemented initial design for enrollment requests.
Updated App.js 
Updated AdminNav.js
Added initial design for EnrollmentRequests.js
> E-2 [FE] Manage Enrollment Requests

- client/src/components/calendar/Calendar.js
- client/src/components/calendar/DateTile.js
- client/src/components/calendar/DaysWeek.js
- client/src/components/calendar/TileEvent.js
- Properly created initial schedule layout
- Switching of months and years should work and calendar for that said month should properly generate
- To access, go to http://localhost:3000/student/schedule
> Created Initial Calendar Layout

- api/routes/v1/file_routes.js
- client/src/pages/public/SignUp.js
- Enhanced file retrieval to list/show all the uploaded files with different categories
> Enhanced file retrieval

- api/prisma/migrations/20250603062505_add_adviser_to_course/migration.sql
- api/prisma/schema.prisma
Add adviserId field and relation between course and users in Prisma schema
> Add adviser relation to course model

- api/controller/course_controller.js
- api/index.js
- api/model/course_model.js
- api/prisma/migrations/20250603062505_add_adviser_to_course/migration.sql
- api/prisma/schema.prisma
- api/routes/v1/course_routes.js
- api/routes/v1/index_routes.js
- client/src/components/modals/courses/CreateCourseModal.js
- client/src/components/modals/courses/EditCourseModal.js
- client/src/pages/admin/CourseManagement.js
Features
- Integrated backend API endpoints for course creation and editing.
- Courses are fetched.
- CreateCourseModal and EditCourseModal is now functional and connected to the backend.
Test Steps
Try creating and editing a course through the UI.
Confirm the course list automatically refreshes after submission.
Verify the payload is sent in mysql
> Integrate backend for course CRUD and UI behavior changes

- client/src/App.js
- client/src/components/modals/transactions/UpdateLedger.js
- client/src/pages/admin/Ledger.js
Added:
- Ledger Screen for Admin
- Update Ledger Modal
> [FE] Ledger (Admin)

- client/src/components/modals/courses/CreateCourseModal.js
- client/src/components/modals/enrollment/AddCourseModal.js
- client/src/pages/admin/CourseManagement.js
- client/src/pages/admin/EnrollmentPeriod.js
implemented frontend enrollment period modal functionality
code cleanup
> implement enrollment period and add course modal functionality

- client/src/components/modals/enrollment/AddAcademicPeriodModal.js
- client/src/components/modals/enrollment/AddCourseModal.js
- client/src/pages/admin/EnrollmentPeriod.js
integrated backend functionality 
Periods are fetched and integration functionality to add courses for that period
> backend integration for academic period courses

- client/src/pages/admin/ManageFees.js
- Changed the UI made it the same with ledger
- Added search function
> [FE] manage-fees_improvement

- api/controller/auth_controller.js
- api/prisma/schema.prisma
- api/routes/v1/auth_routes.js
- client/src/components/modals/manage-accounts/UserAccountDetailsModal.js
- client/src/components/textFields/LabelledInputField.js
- client/src/index.css
- client/src/pages/public/Profile.js
- Added adminResetPassword function to allow administrators to reset user passwords.
- Updated user model to include changePassword field for tracking password changes.
- Enhanced auth routes to include admin password reset endpoint with necessary validations.
- Integrated password reset functionality in UserAccountDetailsModal for user management.
- Improved CSS styles for alert buttons in the modal for better user experience.
> Feature/[A-2] Reset Account Passwords

- client/src/App.js
- client/src/components/modals/home/EditPostModal.js
- client/src/components/post/PostCard.js
- client/src/pages/admin/Archives.js
- client/src/pages/admin/Home.js
- client/src/stores/postsStore.js
- Added functionality to create, edit, hide, unhide, and delete posts in the Home component.
- Added EditPostModal
- Created Archives page
- Integrated Zustand for state management of posts, including visibility and attachment handling.
- Added kebab menu with hide, edit, delete post options.
> [FE] Archives Page - admin

- client/src/App.js
- client/src/components/modals/documents/UpdateRequestModal.js
- client/src/pages/admin/DocumentRequests.js
- client/src/stores/documentRequestStore.js
- client/src/stores/navigationStore.js
- Added admin document requests page
- Added update modal for document request
> [FE] Admin Document Request Screen

- client/src/App.js
- client/src/components/form/DocumentForm.js
- client/src/components/modals/documents/AddNewDocumentModal.js
- client/src/components/modals/documents/EditDocumentModal.js
- client/src/components/tables/ManageDocumentsTable.js
- client/src/pages/admin/ManageDocuments.js
- client/src/stores/manageDocumentsStore.js
- client/src/stores/navigationStore.js
- Added Manage Documents Page
- Added Edit and Add Modal
- Added Manage Documents Store
- Updated Navigation Store
> [FE] Manage Documents Page Admin

- client/src/App.js
- client/src/components/modals/manage-accounts/UserAccountDetailsModal.js
- client/src/pages/admin/AccountManagement.js
- client/src/pages/admin/CreateUser.js
- client/src/pages/admin/DocumentRequests.js
- client/src/pages/admin/ManageDocuments.js
- client/src/stores/createUserStore.js
- client/src/stores/navigationStore.js
- Added create user screen
- Improved ui responsiveness in documents screens
> Feature/[FE] Create User

- client/src/App.js
- client/src/pages/admin/Chatbot.js
- client/src/stores/chatbotStore.js
- client/src/stores/navigationStore.js
> [FE] Chatbot page

- api/controller/post_controller.js
- api/index.js
- api/prisma/migrations/20250912112909_update_post/migration.sql
- api/prisma/schema.prisma
- api/routes/v1/index_routes.js
- api/routes/v1/post_routes.js
- client/src/components/modals/home/CreatePostModal.js
- client/src/components/modals/home/EditPostModal.js
- client/src/components/post/PostCard.js
- client/src/pages/admin/Archives.js
- client/src/pages/admin/Home.js
- client/src/stores/postsStore.js
- client/src/utils/postsApi.js
Added post integration with file upload funtionality.
CRUD for posting with file attachments for the admin.
Updated database schema for posts storage.
> Implement post management features with file handling

- api/controller/post_controller.js
- api/index.js
- api/prisma/migrations/20250912112909_update_post/migration.sql
- api/prisma/schema.prisma
- api/routes/v1/index_routes.js
- api/routes/v1/post_routes.js
- client/src/App.js
- client/src/components/modals/home/CreatePostModal.js
- client/src/components/modals/home/EditPostModal.js
- client/src/components/post/PostCard.js
- client/src/pages/admin/Archives.js
- client/src/pages/admin/Chatbot.js
- client/src/pages/admin/Home.js
- client/src/stores/chatbotStore.js
- client/src/stores/navigationStore.js
- client/src/stores/postsStore.js
- client/src/utils/postsApi.js
* Refactor pagination options, enhance EditPostModal, and update nav components
* Refactor ui in teaching load , teachers documents  page, and signup
* Refactor student Ledger, Assessment, Documents, and StudyLoad components
* Refactor Grades student  UI
* feat: Implement user profile image upload and management
- Added ImageUploadField component for handling profile picture uploads.
- Integrated profile image upload functionality in Profile page using useProfileStore.
- Updated UserDropdown to close compact menu on navigation actions.
- Enhanced Profile page layout and user information display.
- Implemented reset password modal for admin users.
- Added profile picture upload API in userAccountStore.
- Created profileStore for managing profile image state and actions.
* refactor: Remove …
> Dev test (#124)
